# Generated by Django 4.0.2 on 2022-02-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=80)),
                ('VIN', models.CharField(max_length=20)),
                ('Date_of_Purchase', models.IntegerField(max_length=4)),
                ('Date_of_LastService', models.IntegerField(max_length=4)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='clients.client')),
            ],
        ),
    ]
