# Generated by Django 4.0.2 on 2022-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Date_of_LastService',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Date_of_Purchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
