# Generated by Django 4.0.2 on 2022-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_date_of_lastservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Date_of_LastService',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Date_of_Purchase',
            field=models.DateField(),
        ),
    ]
